// import Head from 'next/head';
import '@styles/globals.css';

export const metadata = {
    title: "Financial Landing Page",
    description: "Generated by create next app",
  };
  
  export default function RootLayout({ children }: { children: React.ReactNode }) {
    return (
      <html lang="en">
        <head />
        <body>{children}</body>
      </html>
    );
  }