import Head from 'next/head';
import '@styles/globals.css';

export default function Layout({ children }: { children: React.ReactNode }) {
    return (
    <>
        <Head>
            <title>Financial Landing Page</title>
            <meta name="description" content="Generated by create next app" />
            <meta name="viewport" content="width=device-width, initial-scale=1" />
            <link rel="icon" href="/favicon.ico" />

            {/* Open Graph Meta Tags */}
            <meta property="og:title" content="Financial Landing Page" />
            <meta property="og:description" content="Generated by create next app" />
            <meta property="og:image" content="/favicon.ico" />
            <meta property="og:url" content="https://financial-landing-page.vercel.app/" />
            <meta property="og:type" content="website" />

            {/* Twitter Meta Tags */}
            <meta name="twitter:title" content="Financial Landing Page" />
            <meta name="twitter:description" content="Generated by create next app" />
            <meta name="twitter:image" content="/favicon.ico" />
            {/* Use summary_large_image for larger images */}
            <meta name="twitter:card" content="summary_large_image" />
        </Head>
        <main>
            {children}
        </main>
    </>
    );
}